### ISSUE TITLE
Ben the Buyer

### ISSUE THREAD

**Issue by DaltonElza** [arikrupnik/the-heir#23]
Benny buys other peoples storage units, other peoples problems. He thinks all of his own stuff is worthless, and by extension anything he buys becomes worthless to him when he owns it. But he always thinks everyone else's stuff is better than his, so he keeps buying more. He wouldn't be a member of a club that would have him as a member.

**Comment by arikrupnik** [comment]
Renaming this character to avoid confusion for Penny.
